services:
  - type: web
    name: face-attendence-2
    runtime: docker
    plan: free
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "django-insecure-rr9+5oc%@p^z%^z_wm5!=+ja_q4_ek58u1s4bm-mfejz08b#d!"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: ADMIN_PHONE_NUMBER
        value: "+916281361684"
